jobs:
  test:
    environment:
      NODE_ENV: test
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: NODE_ENV=test yarn test
          name: Run YARN tests
orbs:
  node: circleci/node@3.0.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test